# To properly start the services:
# docker-compose up -d --no-recreate

redis:
  image: redis
  ports:
    - "6379"
  volumes:
    - ./redis:/data

mysql:
  image: mysql
  ports:
    - "3306"
  volumes:
    - ./data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD

participa:
  image: mxabierto/participa
  ports:
    - "8080:80"
  volumes:
    - ./logs:/logs
  links:
    - redis
    - mysql
